services:
  - type: web
    name: image-classifier
    runtime: python
    repo: https://github.com/rabinregmi188/Image-Classifier
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
